name: Update Data

on:
  schedule:
    - cron: '0 */6 * * *'  # Every 6 hours
  workflow_dispatch:

jobs:
  update_data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run presubmit-analysis for ovn-kubernetes
        run: |
          go run ./presubmit-analysis.go ovn-kubernetes
          mv presubmit_jobs.json data/presubmit_jobs_ovn.json


      - name: Run presubmit-analysis for cno
        run: |
          go run ./presubmit-analysis.go cluster-network-operator
          mv presubmit_jobs.json data/presubmit_jobs_cno.json

      - name: Debugging Step
        run: |
          git status
          git log

      - name: Commit and push changes
        env:
          GH_TOKEN: ${{ secrets.REPO_UPDATE }}
        run: |
          git config --local user.email "jluhrsen@redhat.com"
          git config --local user.name "GitHub Action"
          git status
          git add data/
          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            LAST_COMMIT_MSG=$(git log -1 --pretty=%B)
            if [[ "$LAST_COMMIT_MSG" == "Update data files" ]]; then
              echo "Amending to the last commit"
              git commit --amend --no-edit
            else
              echo "Creating a new commit"
              git commit -m "Update data files"
            fi
          fi
          git remote set-url origin https://x-access-token:${GH_TOKEN}@github.com/jluhrsen/PRStats.git
          git fetch
          git rebase
          git push --force-with-lease